### PR TITLE
Creative update

### PR DESCRIPTION
**Pull request by LeMagnesium**
- This PR is for MinetestForFun/server-minetestforfun-creative#57

### CODE REVIEW

**Comment by Ombridride** [comment]
You can merge this PR when you want, just be carful about conflits because it's an old PR.

The creative server isn't very popular, we can do almost what we want on it ;)

**Comment by LeMagnesium** [comment]
I'll update the PR and merge then.

**Comment by Ombridride** [comment]
Ok thank you

**Comment by LeMagnesium** [comment]
It's updated. Do you want to take a look at it?

**Comment by LeMagnesium** [comment]
https://github.com/MinetestForFun/server-minetestforfun/commit/8b02a31c12fe933ab8d7bf5a39c8ab28050a3c93
https://github.com/MinetestForFun/server-minetestforfun/commit/a47360175291680931c7ebbcd93ed33bbf273ab5

**Pull request closed without merging**
