### PR TITLE
removing 200+ skin and renaming

### PR DESCRIPTION
**Pull request by ezamlinux**
Deleting of 200+ skin and renaming 

I also made the changes suggested by @ObaniGemini 

(If everything is OK , great thanks for your help ...  i have some difficulties with GIT )

### CODE REVIEW

**Comment by Ombridride** [comment]
+1 for me, no particular comments to add

**Comment by LeMagnesium** [comment]
Everything seems fine. :+1:

**Comment by ObaniGemini** [comment]
**REPOST**

I think we can trash *"mff_character_1"*, *"mff_character_3"*, *"mff_character_6"*, *"mff_character_7"*, *"mff_character_11"* and *"character_11"*, because they're kinda ugly.

I would replace them with:

- `"character_33"`
- `"character_28"`
- `"character_67"`
- `"character_123"`
- `"character_265"` ou `"character_273"`
- `"character_282"`
- `"character_504"`
I think we need some "fun" skins (like *504* and *123*)

***This was approved by @Ombridride because I made those skins and I personally think they're ugly/unusable (and they're not used, indeed)***

**Comment by ezamlinux** [comment]
@LeMagnesium I worked on a fresh clone of MFF so everything was up to date. ( i  push a specific branch , my master is old )

@ObaniGemini i have made the changes you proposed.

**Comment by Ombridride** [comment]
Waiting @crabman or ObaniGemini approvments

**Comment by Crabman** [comment]
Hello guys , I don't think i'm the right Crabman, you keep tagging me but I don't play Minecraft anymore :)
Please check your spelling ;)

See ya and have fun !

**Comment by ObaniGemini** [comment]
For me it's a :+1: :+1: :)

**Comment by ObaniGemini** [comment]
By the way, will we need to make aliases for players using deleted skins ? Or will it be set to default automaticaly ?

**Comment by Ombridride** [comment]
Need confirmation, but normally it's a "grey"(transparent) skin until the player change again his skin

**Comment by ezamlinux** [comment]
@ObaniGemini @Ombridride 

There are 2 potential situation 

firstly : the player uses a skin with "ID" > 50 , then this skin will by default 
Secondly : If he used a skin's ID  <50 , the new skin at this number. (or, by chance it will have its original skin if the number has not changed )

**Comment by ObaniGemini** [comment]
Or make aliases for if *number* > 50, set skin to "character_1"
(there might be some kind of str("character_", str(number)) in the code I think)

**Comment by LeMagnesium** [comment]
> Or make aliases for if number > 50, set skin to "character_1"

Just reset everyone's skin. They'll figure out they need to pick a new one.

**Comment by LeMagnesium** [comment]
There, [patch merged](https://github.com/MinetestForFun/server-minetestforfun/commit/5079f3c35d2387a6f33d129a6e91f8877ff2dcf1)

**Pull request closed without merging**
