### PR TITLE
50 Skin u_skin

### PR DESCRIPTION
**Pull request by ezamlinux**
Deleting of 200+ skin and renaming ( 36 MT character, whose 8 girl + 14 MFF character )

### CODE REVIEW

**Comment by ezamlinux** [comment]
WOW ! Can i have a support for my PR ... because i don't understand .. i rebase before work and i see crabman's commit for submodule ... i don't understand this wave of commits ...

**Comment by LeMagnesium** [comment]
I think you should update your clone first. I can extract your commit, but it would be cleaner to have your master branch identical to ours, and your commit in a different branch.
We could meet on IRC for assistance (if you have the time for that).

**Comment by ObaniGemini** [comment]
Je pense qu'on peut virer "mff_character_1", "mff_character_3", "mff_character_6", "mff_character_7", "mff_character_11" et "character_11".

Je les remplacerai par (par exemple):
- "character_33"
- "character_28"
- "character_67"
- "character_123"
- "character_265" ou "character_273"
- "character_282"
- "character_504"

Je pense qu'il faut aussi quelques persos "fun" (d'où *504* et *123*)

**Comment by Ombridride** [comment]
@ezamlinux Thank you for this PR

@ObaniGemini 
There are less than 50 skins so i think we can add the @ObaniGemini characters suggested without deleting other characters

@ezamlinux @LeMagnesium 
For the PR, I think we need to redo it, without being nasty it's a really mess...

**Comment by Ombridride** [comment]
Rejected/Closed because now here : https://github.com/MinetestForFun/server-minetestforfun/pull/477

**Pull request closed without merging**
