### PR TITLE
All in one cart/rail patch

### PR DESCRIPTION
**Pull request by Coethium**
Here is another all-in-one patch, concerning three discuss : #496 #492 #366 

* Removed PilzAdam's carts
* Replaced by SmallJoker's Boost_cart (very very better with CPU !)
(https://github.com/SmallJoker/boost_cart)
* Modified to fully replace carts
* Modified for MFF :
- desactivate mesecons
- power_rail: accelerate, max_speed set in init.lua
- brake_rail: deccelerate, min_speed set in init.lua (so the cart
doesn't stop and runs at very low speed)
- default:rail / rail_cooper : no friction, keep the current speed
- no collision (avoid the "walled_in" bug)

### CODE REVIEW

**Comment by Darcidride** [comment]
Awesome work, seems perfect to me ! :)

Need the @crabman77 @LeMagnesium opinions

**Comment by AcidNinjaFWHR** [comment]
We need to test that on the server :)

**Comment by Coethium** [comment]
Yes, it needs to be tested on a real server <-> client configuration. In local it was tested with a velocity about 100 times the walk speed. The cart keeps going out of the rails sometime, but it is quicky replaced on the rail.

**Comment by crabman77** [comment]
Voir avec @Cyberpangolin pour tester sur chlorine.

**Comment by Darcidride** [comment]
Merged, congratulation :)

**Comment by Cyberpangolin** [comment]
Tested ingame, works almost perfectly!
:+1: 

Thanks for the patch!

**Pull request merged**
