### PR TITLE
Add falling_extras mod

### PR DESCRIPTION
**Pull request by HybridDog**

### CODE REVIEW

**Comment by ObaniGemini** [comment]
This would be a great idea, but please... squash your commits :D

**Comment by HybridDog** [comment]
done

**Comment by LeMagnesium** [comment]
I don't see any problem with that code. If the other developers have no issue with adding that mod then I'm fine with it.

**Comment by ObaniGemini** [comment]
@Ombridride and @crabman77 told they were against adding this mod to the server. Maybe they will share their opinion on it there.

**Comment by Ombridride** [comment]
Hi,

Thank you for this issue @HybridDog 

But :
- I'm afraid of the lag it can add on our server (mainly because of, node destroy under the falling sand/gravel column)
- usebug possible ? (node destroy under the falling sand/gravel column)
- How many damages the player takes with our gravity tweaks ?
- The inverted gravel/sand falling isn't useful in my point of view

Can you explain more your PR and why you post it on our classic server ? I want more explanation please :)

**Comment by HybridDog** [comment]
lt doesn't add lag, it overrides the on_step of the falling entity, it doesn't increase it.
https://github.com/minetest/minetest/blob/master/builtin/game/falling.lua#L43

l didn't find bugs, l don't remember exactly maybe falling extras fixes a bug: by default falling sand can fall into not walkable not buildable_to nodes and replace them l think. You could try it, add a node where you can walk through but which is not buildable_to and make sand fall into it.

The damage depends on its speed when hurting ground l think. It would be difficult to use it as weapon.

l doubt someone changes the gravity to make players (and falling nodes) fall up, but if he/she does it, there shouldn't be many objects which don't become removed and add the node that the object removing starts.


l think falling nodes should play sounds and cause damage when touching ground instead of quietly setting a node.

**Comment by LeMagnesium** [comment]
I will conduct tests tomorrow ; though I doubt that @HybridDog is wrong in saying that there will not be any additional lag. I just have to fix something, it seems one of our mods (probably builtin_falling) overwrites the redefinition of __builtin:falling made in this mod.

**Comment by HybridDog** [comment]
thanks, l'm not sure, l think l read somewhere that if the acceleration of the falling entity is not set in the on_step function but only in the on_activate, the entity looks like it falls immediately and not liquidly, l'm wondering how this could be true

**Comment by LeMagnesium** [comment]
> l'm wondering how this could be true

I have no idea how it could make sense.

What I do know is that your mod doesn't bring significant lag. However, I'll have to modify it to call the previous on_step function set in builtin_falling which prevents people from dropping falling nodes in protected areas.

**Comment by LeMagnesium** [comment]
After researching a bit it appears that we can either :
 - Merge builtin_fallings's protection in your mod
 - Remove builtin_falling's protection from the repo (which is not gonna happen)
 - Not merge your mod

Sadly those are the only choices available, and considering the rewards from merging your mod they do not really balance with merging the sh*t from builtin_falling it in..

**Comment by HybridDog** [comment]
des PR muas ma nei macha, da gabs Änderungen: https://github.com/HybridDog/falling_extras/commit/60e721f132003380e4a0c5645120face2959f371

**Comment by LeMagnesium** [comment]
Even with the PR being outdated due to modifications, we finally decided to not include this mod... Our server is dealing with extreme lags and overbloating of mods, so adding more of them is not recommended...
Good work though; good luck for this mod's future versions.

**Comment by HybridDog** [comment]
ok,
LeMagnesium, l use a lot mods:
screenshot_20160506_160852

my version of PilzAdam's TNT mod currently works extremely fast, it even uses the function_delayer mod which works like a scheduler, i.e. tnt nodes could constantly happen everywhere and you can still play completely liquidly, l tested it.

**Pull request closed without merging**
